extracting the dataset from NAS ...
done
/var/spool/slurm/d/job00402/slurm_script: line 22: $'\necho \'setup yolox environment ...\'\npip3 install -v -e .  # or  python3 setup.py develop\necho \'done\'\n': command not found
20221107-134453
Traceback (most recent call last):
  File "/data/happyhoo97/anaconda3/envs/yolox_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/happyhoo97/anaconda3/envs/yolox_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/happyhoo97/repos/YOLOX/tools/eval.py", line 203, in <module>
    exp.merge(args.opts)
  File "/data/happyhoo97/repos/YOLOX/yolox/exp/base_exp.py", line 64, in merge
    assert len(cfg_list) % 2 == 0
AssertionError
done
